version: "3.9"

services:
  bot:
    build:
      context: .
    image: andreygolovin5/telegrambot_time
    env_file:
      - .env
    restart: always
    depends_on:
      - tgbot
    command: >
      sh -c "cd ./bot && cd ../. && python bot/bot.py"
  tgbot:
    image: postgres:15.1-alpine
    environment:
      POSGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  data:
