jobs:
  - job_name: database
    collectors: [database]
    static_configs:
      - targets:
          tgbot: 'postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:5432/$POSTGRES_DB?sslmode=disable&lock_timeout=5000'

collectors:
  - collector_name: database
    metrics:
      - metric_name: pg_db_stat_user_tables_seq_scan
        type: counter
        help: 'Number of sequential scans initiated on this table'
        key_labels:
          - schema
          - table
        values:
          - seq_scan
        query: |
          SELECT schemaname AS schema, relname AS table, seq_scan
          FROM pg_stat_user_tables
          WHERE schemaname NOT IN ('pg_catalog', 'information_schema')
          
      - metric_name: pg_db_size_bytes
        type: gauge
        help: 'Database size in bytes'
        values:
          - size
        query: "SELECT pg_database_size(current_database()) AS size"
        
      - metric_name: pg_db_connections
        type: gauge
        help: 'Active connections to this database'
        values:
          - count
        query: |
          SELECT COUNT(*) AS count 
          FROM pg_stat_activity 
          WHERE datname = current_database()

      - metric_name: count_users
        type: gauge
        help: 'Is count_users in table users'
        values:
          - count
        query: |
          SELECT COUNT(*) AS count FROM users

      - metric_name: pg_server_connections_total
        type: gauge
        help: 'Total connections to the server'
        key_labels:
          - state
        values:
          - count
        query: |
          SELECT state, COUNT(*) AS count
          FROM pg_stat_activity
          GROUP BY state
          
      - metric_name: pg_server_database_size_bytes
        type: gauge
        help: 'Size of all databases in bytes'
        key_labels:
          - datname
        values:
          - size
        query: SELECT datname, pg_database_size(datname) AS size FROM pg_database