name: Build and deploy workflow
on:
  push:
    branches:
      - main
jobs:
  build_and_push:
    runs-on: ubuntu-24.04
    steps:
      - name: clone code
        uses: actions/checkout@v3
      - name: docker build
        run: docker build -t andreygolovin5/telegrambot_time:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push andreygolovin5/telegrambot_time:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  deploy:
    runs-on: ubuntu-24.04
    needs: build_and_push
    env:
      API_TOKEN: ${{ secrets.API_TOKEN }}
      ADMIN_ID: ${{ secrets.ADMIN_ID }}
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      PRODUCTION_CALENDAR: ${{ secrets.PRODUCTION_CALENDAR }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
    steps:
      - name: clone code
        uses: actions/checkout@v3
      - name: render configs
        run: |
          mkdir deploy
          cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yml
          cp -R sql_exporters/ deploy/
          cp -R prometheus/ deploy/
      - name: copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "deploy/"
          target: "appbot"
          strip_components: 1
      - name: deploy appbot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd appbot
            echo ${{ secrets.PASSWORD }} | sudo -S docker-compose down
            echo ${{ secrets.PASSWORD }} | sudo -S docker-compose up -d